# -*- coding: utf-8 -*-
"""LeNet(CNN) From Scratch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fnB9uL1gIi0tBx6CvHcV6RXubO1NChGT
"""

import numpy as np
import sklearn
from keras import datasets
import matplotlib.pyplot as plt
from keras.utils.np_utils import to_categorical
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.models import Sequential
from keras.optimizers import Adam
from keras.layers import Dense
from keras.layers import Dropout

(X_train, y_train), (X_test, y_test) = datasets.mnist.load_data()

plt.imshow(X_train[0])
print('This is a',y_train[0])
plt.show()

images_per_class = []

cols = 5
classes = 10
fig, axes = plt.subplots(nrows = classes, ncols = cols, figsize = (6,10))
fig.tight_layout()

for i in range(cols):
  for j in range(classes):
    x_selected = X_train[y_train == j]
    axes[j][i].imshow(x_selected[np.random.randint(0,x_selected.shape[0]-1)], cmap = plt.get_cmap('gray'))
    axes[j][i].axis('off')
    
    if i == 2:
      axes[j][i].set_title('Class: '+ str(j))
      images_per_class.append(x_selected.shape[0])

# Checking the number of images per class

plt.bar(list(range(0,classes)), images_per_class)
plt.xlabel('Class Label')
plt.ylabel('Number of Images')
plt.show()

#One Hot Encoding the class labels

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Normalizing all images on a scale of 0 to 1

X_train = X_train/255
X_test = X_test/255

#Reshaping the input for feeding into the network as a flat 2D array

n_pixels = 784
X_train = X_train.reshape(X_train.shape[0], 28,28,1)
X_test = X_test.reshape(X_test.shape[0], 28,28,1)

X_train.shape
y_train.shape

adam = Adam(lr = 0.001)
def LeNet():
  model = Sequential()
  model.add(Conv2D(30, (5,5), input_shape = (28,28,1), activation='relu'))
  model.add(MaxPooling2D(pool_size = (2,2)))
  model.add(Conv2D(15, (3,3), activation= 'relu'))
  model.add(MaxPooling2D(pool_size=(2,2)))
  model.add(Flatten())
  model.add(Dense(500, activation = 'relu'))
  model.add(Dropout(0.5))
  model.add(Dense(classes, activation = 'softmax'))
  model.compile(optimizer = adam, loss = 'categorical_crossentropy', metrics = ['accuracy'])
  return model

LeNet().summary()

model = LeNet()
h = model.fit(X_train, y_train, epochs = 10,batch_size = 10,  verbose = 1, validation_split = 0.1, shuffle=True)

plt.plot(h.history['accuracy'])
plt.plot(h.history['val_accuracy'])
plt.legend(['Train','Validaiton'])
plt.title('Accuracies')
plt.xlabel('Epochs')

plt.plot(h.history['loss'])
plt.plot(h.history['val_loss'])
plt.legend(['Train', 'Validaiton'])
plt.title('Loss')
plt.xlabel('Epochs')

import requests
from PIL import Image
URL = 'https://www.researchgate.net/profile/Jose_Sempere/publication/221258631/figure/fig1/AS:305526891139075@1449854695342/Handwritten-digit-2.png'
response = requests.get(URL, stream = True)
image = Image.open(response.raw)
plt.imshow(image)

import cv2

img_array = np.asarray(image)
img = cv2.resize(img_array, (28,28,))
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = cv2.bitwise_not(img)
plt.imshow(img, cmap = plt.get_cmap('gray'))

img = img/255

img = img.reshape(1,28,28,1)
print('This is the number ',np.argmax(model.predict(img)))

#Model Evaluation
score = model.evaluate(X_test, y_test)

print('Model generalization error is ', score[0])
print('Model generalization accuracy is ', score[1])

#Visualizing the Convolutional Layers 
from keras.models import Model

layer1 = Model(inputs = model.layers[0].input, outputs = model.layers[0].output)
layer2 = Model(inputs = model.layers[0].input, outputs = model.layers[2].output)

visual1 = layer1.predict(img)
visual2 = layer2.predict(img)

plt.figure(figsize=(10,5))
for i in range(visual1.shape[3]):
  plt.subplot(3,10, i+1)
  plt.imshow(visual1[0,:,:,i])
  plt.suptitle('Layer 1')
  plt.axis('off')

plt.figure(figsize=(10,5))
for i in range(visual2.shape[3]):
  plt.subplot(3,10, i+1)
  plt.imshow(visual2[0,:,:,i])
  plt.suptitle('Layer 2')
  plt.axis('off')

